In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("Housing.csv")
df.head()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no

In [3]:
from sklearn.compose import make_column_transformer
## make colmun transform -> seleted colmuns only are encoded and passthough are not 
ohc = OneHotEncoder(sparse_output=False).set_output(transform='pandas')
ct = make_column_transformer((ohc, ['driveway','recroom','fullbase','gashw','airco','prefarea']),
                            ('passthrough',['price','lotsize','bedrooms','bathrms','stories','garagepl']))

ct = ct.set_output(transform='pandas')
dum_df_1 = ct.fit_transform(df)
dum_df_1

,onehotencoder__driveway_no,onehotencoder__driveway_yes,onehotencoder__recroom_no,onehotencoder__recroom_yes,onehotencoder__fullbase_no,onehotencoder__fullbase_yes,onehotencoder__gashw_no,onehotencoder__gashw_yes,onehotencoder__airco_no,onehotencoder__airco_yes,onehotencoder__prefarea_no,onehotencoder__prefarea_yes,passthrough__price,passthrough__lotsize,passthrough__bedrooms,passthrough__bathrms,passthrough__stories,passthrough__garagepl
0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,42000.0,5850,3,1,2,1
1,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,38500.0,4000,2,1,1,0
2,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,49500.0,3060,3,1,1,0
3,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,60500.0,6650,3,1,2,0
4,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,61000.0,6360,2,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,91500.0,4800,3,2,4,0
542,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,94000.0,6000,3,2,4,0
543,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,103000.0,6000,3,2,4,1
544,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,105000.0,6000,3,2,2,1
545,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,105000.0,6000,3,1,2,1

In [4]:
dum_df_2 =pd.get_dummies(df,drop_first=True)
dum_df_2

,price,lotsize,bedrooms,bathrms,stories,garagepl,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes
0,42000.0,5850,3,1,2,1,True,False,True,False,False,False
1,38500.0,4000,2,1,1,0,True,False,False,False,False,False
2,49500.0,3060,3,1,1,0,True,False,False,False,False,False
3,60500.0,6650,3,1,2,0,True,True,False,False,False,False
4,61000.0,6360,2,1,1,0,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,0,True,True,False,False,True,False
542,94000.0,6000,3,2,4,0,True,False,False,False,True,False
543,103000.0,6000,3,2,4,1,True,True,False,False,True,False
544,105000.0,6000,3,2,2,1,True,True,False,False,True,False
545,105000.0,6000,3,1,2,1,True,False,False,False,True,False

In [14]:
### verbose_feature_names_out will not allow make_column_transformer to apply prefix eg. passthrough__lotsize -> lotsize

In [5]:
ohc = OneHotEncoder(sparse_output=False).set_output(transform='pandas')
ct = make_column_transformer((ohc, ['driveway','recroom','fullbase','gashw','airco','prefarea']),
                            ('passthrough',['price','lotsize','bedrooms','bathrms','stories','garagepl']),verbose_feature_names_out=False)

ct = ct.set_output(transform='pandas')
dum_df_3 = ct.fit_transform(df)
dum_df_3

,driveway_no,driveway_yes,recroom_no,recroom_yes,fullbase_no,fullbase_yes,gashw_no,gashw_yes,airco_no,airco_yes,prefarea_no,prefarea_yes,price,lotsize,bedrooms,bathrms,stories,garagepl
0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,42000.0,5850,3,1,2,1
1,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,38500.0,4000,2,1,1,0
2,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,49500.0,3060,3,1,1,0
3,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,60500.0,6650,3,1,2,0
4,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,61000.0,6360,2,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,91500.0,4800,3,2,4,0
542,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,94000.0,6000,3,2,4,0
543,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,103000.0,6000,3,2,4,1
544,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,105000.0,6000,3,2,2,1
545,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,105000.0,6000,3,1,2,1

In [6]:
X = dum_df_2.drop('price',axis=1)
y = dum_df_2['price']

In [7]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X,y)

LinearRegression()

In [12]:
## unlabelled data 
tst = pd.read_csv('tst_Housing.csv')
dum_tst_2 = pd.get_dummies(tst, drop_first=True)
y_pred = lr.predict(dum_tst_2)
##  num of  columns in .fit(x,y) and .predict()  must match

ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- airco_yes
- driveway_yes
- gashw_yes
- prefarea_yes

## Now Solution =>>>

### Using column Transformer

In [8]:
ohc = OneHotEncoder(sparse_output=False, drop='first').set_output(transform='pandas')
ct = make_column_transformer((ohc, ['driveway','recroom','fullbase','gashw','airco','prefarea']),
                            ('passthrough',['lotsize','bedrooms','bathrms','stories','garagepl']),verbose_feature_names_out=False)

## price colmun is not inlcuded

In [9]:
X = df.drop('price', axis=1)
y = df['price']

In [10]:

ct = ct.set_output(transform='pandas')
x_trans = ct.fit_transform(X)
x_trans.columns

Index(['driveway_yes', 'recroom_yes', 'fullbase_yes', 'gashw_yes', 'airco_yes',
       'prefarea_yes', 'lotsize', 'bedrooms', 'bathrms', 'stories',
       'garagepl'],
      dtype='object')

In [13]:
## unlabelled data 
tst = pd.read_csv('tst_Housing.csv')
tst_trans = ct.transform(tst)
tst_trans.columns
##  num of  columns in .fit(x,y) and .predict()  must match

Index(['driveway_yes', 'recroom_yes', 'fullbase_yes', 'gashw_yes', 'airco_yes',
       'prefarea_yes', 'lotsize', 'bedrooms', 'bathrms', 'stories',
       'garagepl'],
      dtype='object')

In [14]:
# Linear Regression
lr = LinearRegression()
lr.fit(x_trans, y)

y_pred = lr.predict(tst_trans)
y_pred

array([65151.39992985, 42650.08901117, 41137.92877603, 76249.38318098])

In [15]:
## Using Pipeline
from sklearn.pipeline import Pipeline

pipe = Pipeline([('TRNS', ct),('LR', lr)])
pipe.fit(X,y)
y_pred_pipe = pipe.predict(tst)
y_pred_pipe

array([65151.39992985, 42650.08901117, 41137.92877603, 76249.38318098])